apiVersion: v1
kind: Secret
metadata:
  name: juice-shop-encryptionkeys
  namespace: juice-shop
type: Opaque
stringData:
  jwt.pub: |
    -----BEGIN RSA PUBLIC KEY-----
    MIGJAoGBAM3CosR73CBNcJsLv5E90NsFt6qN1uziQ484gbOoule8leXHFbyIzPQRozgEpSpiwhr6d2/c0CfZHEJ3m5tV0klxfjfM7oqjRMURnH/rmBjcETQ7qzIISZQ/iptJ3p7Gi78X5ZMhLNtDkUFU9WaGdiEb+SnC39wjErmJSfmGb7i1AgMBAAE=
    -----END RSA PUBLIC KEY-----
  premium.key: |
    1337133713371337.EA99A61D92D2955B1E9285B55BF2AD42
