apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juice-shop-data
  namespace: juice-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # OKE geralmente usa uma StorageClass padr√£o.
  # Se precisar fixar, descomente e ajuste:
  # storageClassName: oci-bv
